### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by jplopezy** [molu8bits/modsecurity-parser#17]
Team,

Excellent tool. For some reason when I want to generate the image or the excel gives me an error.

Is it a compatibility issue or does the log have something difficult to partial?

What is the level of debugging desired by the tool?

command line :  python3 modsecurity-parser.py -x 1.xls -g 1.png --jsonaudit --jsononeperline --version3   -f modsec_audit.log

Exception in Graph TOP 10 Attacks intercepted 'audit_data'
Exception in Graph TOP 10 IP source addresses 'remote_address'
Exception in TOP 20 rule hits 'audit_data'
for transaction_id : -
Exception in Graph TOP 10 Attacks intercepted 'audit_data'
Traceback (most recent call last):
  File "modsecurity-parser.py", line 689, in <module>
    outputWithGraphs = modsecViewGraphs(modsec_entries)
  File "modsecurity-parser.py", line 359, in modsecViewGraphs
    event_times1 = np_event_time_action[:, 0]

regards

**Comment by molu8bits** [comment]
Sometimes it can stuck if the log is incomplete, but shoud rather skip such entry. You can pick a line or few of them and run scripts on limited data. You can anonymize your log and send me then I could check what is the problem.
