### ISSUE TITLE
ValueError: Single argument to subplot must be a three-digit integer, not <Axes: >

### ISSUE THREAD

**Issue by shaund-teqcle-co-za** [molu8bits/modsecurity-parser#35]
First time clone, install pre-requisites and run. It simply throws a stack trace:

> [shaund@peregrine modsecurity-parser]$ python3 modsecurity_parser.py -f /home/shaund/tmp/mod_sec/modsec_audit.log
input_filename: /home/shaund/tmp/mod_sec/modsec_audit.log
----- modsec_audit events processed: 990 -----
----- modsec_audit events skipped by INCLUDED/EXCLUDED options or INVALID: 0 -----
Traceback (most recent call last):
  File "/home/shaund/Software/modsecurity-parser/modsecurity_parser.py", line 864, in <module>
    output_with_graphs = modsec_view_graphs(modsec_entries)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shaund/Software/modsecurity-parser/modsecurity_parser.py", line 565, in modsec_view_graphs
    plt.subplot(ax21)
  File "/usr/lib64/python3.11/site-packages/matplotlib/pyplot.py", line 1323, in subplot
    key = SubplotSpec._from_subplot_args(fig, args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/matplotlib/gridspec.py", line 575, in _from_subplot_args
    raise ValueError(
ValueError: Single argument to subplot must be a three-digit integer, not <Axes: >

**Comment by molu8bits** [comment]
Might be it fails due to Python 3.11. It hasn't been tested with this version yet.

**Comment by shaund-teqcle-co-za** [comment]
Thanks molu8bits. I ran it on Python 3.9.16 and it runs fine.
