### ISSUE TITLE
TypeError: 'set' object does not support indexing

### ISSUE THREAD

**Issue by stAn47** [molu8bits/modsecurity-parser#4]
hello, i am trying to see what your script does, but i am now getting: 

TypeError: 'set' object does not support indexing

```
Traceback (most recent call last):
  File "modsecurity-parser.py", line 683, in <module>
    outputWithGraphs = modsecViewGraphs(modsec_entries)
  File "modsecurity-parser.py", line 434, in modsecViewGraphs
    ex.plot(ax=ax1, kind='bar', title=plot_title, stacked=True, color={'purple', 'red'}, fontsize=7, rot=45)
  File "/usr/lib/python3/dist-packages/pandas/tools/plotting.py", line 3671, in __call__
    sort_columns=sort_columns, **kwds)
  File "/usr/lib/python3/dist-packages/pandas/tools/plotting.py", line 2556, in plot_frame
    **kwds)
  File "/usr/lib/python3/dist-packages/pandas/tools/plotting.py", line 2384, in _plot
    plot_obj.generate()
  File "/usr/lib/python3/dist-packages/pandas/tools/plotting.py", line 987, in generate
    self._make_plot()
  File "/usr/lib/python3/dist-packages/pandas/tools/plotting.py", line 1890, in _make_plot
    kwds['color'] = colors[i % ncolors]
TypeError: 'set' object does not support indexing
```

i am not 100% sure that i installed all required python3.5 modules on my ubuntu16.04  (if you know exact names of them per apt installer it would be nice)

```
apt-get install python3-openpyxl  python3-numexpr python3-pandas python3-matplotlib 
```

thank you for any info, stan

**Comment by molu8bits** [comment]
This install libraries for Ubuntu18 and Ubuntu16
`
apt-get install python3-openpyxl  python3-numpy python3-pandas python3-matplotlib
`
But Ubuntu16 comes with old matplotlib and pandas libraries.
If you installed them by command apt from repositories you can update them using pip3 by following commands:

```
apt install python3-pip
pip3 install --upgrade pandas
pip3 install --upgrade matplotlib
```
After such upgrade modsecurity-parser.py should work fine.
